//
//  TodoDetailInteractor.swift
//  TodoCleanSwiftSample
//
//  Created by 60067667 on 2021/01/20.
//  Copyright (c) 2021 Nali. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TodoDetailBusinessLogic
{
  func doSomething(request: TodoDetail.Something.Request)
}

protocol TodoDetailDataStore
{
  //var name: String { get set }
}

class TodoDetailInteractor: TodoDetailBusinessLogic, TodoDetailDataStore
{
  var presenter: TodoDetailPresentationLogic?
  var worker: TodoDetailWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: TodoDetail.Something.Request)
  {
    worker = TodoDetailWorker()
    worker?.doSomeWork()
    
    let response = TodoDetail.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
