//
//  TodoDetailWorker.swift
//  TodoCleanSwiftSample
//
//  Created by 60067667 on 2021/01/20.
//  Copyright (c) 2021 Nali. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class TodoDetailWorker
{
     var todoStore: TodoStoreProtocol

    init(todoStore: TodoStoreProtocol) {
        self.todoStore = todoStore
    }

    func updateTodo(todoToUpdate: Todo, completionHandler: @escaping (Todo?) -> Void)
    {
        todoStore.updateTodo(todoToUpdate: todoToUpdate) { (todo: () throws -> Todo?) in
            do {
                let todo = try todo()
                DispatchQueue.main.async {
                    completionHandler(todo)
                }
            } catch {
                DispatchQueue.main.async {
                    completionHandler(nil)
                }
            }
        }
    }
}

protocol TodoStoreProtocol {
    func updateTodo(todoToUpdate: Todo, completionHandler: @escaping (() throws -> Todo?) -> Void)
}
