//
//  TodoDetailRouter.swift
//  TodoCleanSwiftSample
//
//  Created by 60067667 on 2021/01/20.
//  Copyright (c) 2021 Nali. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol TodoDetailRoutingLogic
{
  func routeToTodoList(segue: UIStoryboardSegue?)
}

protocol TodoDetailDataPassing
{
  var dataStore: TodoDetailDataStore? { get }
}

class TodoDetailRouter: NSObject, TodoDetailRoutingLogic, TodoDetailDataPassing
{
  weak var viewController: TodoDetailViewController?
  var dataStore: TodoDetailDataStore?
  
  // MARK: Routing

    func routeToTodoList(segue: UIStoryboardSegue?) {
        if let segue = segue {
            let destinationVC = segue.destination as! TodoListViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToTodoList(source: dataStore!, destination: &destinationDS)
        } else {
            let index = viewController!.navigationController!.viewControllers.count - 2
            let destinationVC = viewController?.navigationController?.viewControllers[index] as! TodoListViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToTodoList(source: dataStore!, destination: &destinationDS)
            navigateToTodoList(source: viewController!, destination: destinationVC)
        }
    }

  // MARK: Navigation
  
  func navigateToTodoList(source: TodoDetailViewController, destination: TodoListViewController)
  {
    source.navigationController?.popViewController(animated: true)
  }
  
  // MARK: Passing data
  
  func passDataToTodoList(source: TodoDetailDataStore, destination: inout TodoListDataStore)
  {
//    destination.
  }
}
