//
//  TodoDetailViewController.swift
//  TodoCleanSwiftSample
//
//  Created by 60067667 on 2021/01/20.
//  Copyright (c) 2021 Nali. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TodoDetailDisplayLogic: class
{
    func displayAddTodo(viewModel: TodoDetail.AddTodo.ViewModel)
    func displayUpdateTodo(viewModel: TodoDetail.UpdateTodo.ViewModel)
}

class TodoDetailViewController: UIViewController, TodoDetailDisplayLogic
{
    var interactor: TodoDetailBusinessLogic?
    var router: (NSObjectProtocol & TodoDetailRoutingLogic & TodoDetailDataPassing)?

    // MARK: Object lifecycle

    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
    {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }

    required init?(coder aDecoder: NSCoder)
    {
        super.init(coder: aDecoder)
        setup()
    }

    // MARK: Setup

    private func setup()
    {
        let viewController = self
        let interactor = TodoDetailInteractor()
        let presenter = TodoDetailPresenter()
        let router = TodoDetailRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }

    // MARK: Routing

    override func prepare(for segue: UIStoryboardSegue, sender: Any?)
    {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }

    // MARK: View lifecycle

    override func viewDidLoad()
    {
        super.viewDidLoad()


    }

    // MARK: Do something

    @IBOutlet weak var todoDetailTextView: UITextView!

    @IBAction func touchSaveButton(_ sender: Any) {
        let todoContent = todoDetailTextView.text!
        //        if let todoToEdit = interactor?.todoToEdit {
        let isDone = false
        let request = TodoDetail.AddTodo.Request(todo: TodoDetail.TodoFormFields(todoContent: todoContent, isDone: isDone))
        interactor?.addTodo(request: request)
        //        }
    }

    func displayAddTodo(viewModel: TodoDetail.AddTodo.ViewModel) {
        if !viewModel.todos.isEmpty {
            router?.routeToTodoList(segue: nil)
        }
    }

    func displayUpdateTodo(viewModel: TodoDetail.UpdateTodo.ViewModel)
    {
        router?.routeToTodoList(segue: nil)
        //    if viewModel.todo != nil {
        //        router?.routeToTodoList(segue: nil)
        //    } else {
        //        showTodoFailureAlert(title: "Failed to create todo", message: "Please correct your todo and submit again.")
        //    }
    }


    // Error handling
    private func showTodoFailureAlert(title: String, message: String)
    {
        let alertController = UIAlertController(title: title, message: message, preferredStyle: .alert)
        let alertAction = UIAlertAction(title: "OK", style: .default, handler: nil)
        alertController.addAction(alertAction)
        showDetailViewController(alertController, sender: nil)
    }
}
