//
//  TodoDetailPresenter.swift
//  TodoCleanSwiftSample
//
//  Created by 60067667 on 2021/01/20.
//  Copyright (c) 2021 Nali. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TodoDetailPresentationLogic
{
    func presentAddTodo(response: TodoDetail.AddTodo.Response)
    func presentGetTodo(response: TodoDetail.GetTodo.Response)
    func presentUpdateTodo(response: TodoDetail.UpdateTodo.Response)
}

class TodoDetailPresenter: TodoDetailPresentationLogic
{
    weak var viewController: TodoDetailDisplayLogic?

    // MARK: Do something

    func presentAddTodo(response: TodoDetail.AddTodo.Response)
    {
        let viewModel = TodoDetail.AddTodo.ViewModel(todos: response.todos)
        viewController?.displayAddTodo(viewModel: viewModel)
    }

    func presentGetTodo(response: TodoDetail.GetTodo.Response) {
        let viewModel = TodoDetail.GetTodo.ViewModel(displayedTodo: TodoDetail.GetTodo.ViewModel.DisplayedTodo(todoContent: response.todo?.todoContent ?? ""))
        viewController?.displayGetTodo(viewModel: viewModel)
    }

    func presentUpdateTodo(response: TodoDetail.UpdateTodo.Response)
    {
        let viewModel = TodoDetail.UpdateTodo.ViewModel(todos: response.todos)
        viewController?.displayUpdateTodo(viewModel: viewModel)
    }
}
