//
//  TodoDetailInteractor.swift
//  TodoCleanSwiftSample
//
//  Created by 60067667 on 2021/01/20.
//  Copyright (c) 2021 Nali. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TodoDetailBusinessLogic
{
    var todoToEdit: Todo? { get }
    func addTodo(request: TodoDetail.AddTodo.Request)
    func updateTodo(request: TodoDetail.UpdateTodo.Request)
    func getTodo(request: TodoDetail.GetTodo.Request)
}

protocol TodoDetailDataStore
{
    var todoToEdit: Todo? { get set }
    var todos: [Todo]? { get set }
}

class TodoDetailInteractor: TodoDetailBusinessLogic, TodoDetailDataStore
{
    var presenter: TodoDetailPresentationLogic?
    var worker: TodosWorker?
    var todoToEdit: Todo?

    var todos: [Todo]? // 업데이트 된 todo

    // MARK: Do something

    func addTodo(request: TodoDetail.AddTodo.Request) {
        let todoToAdd = buildTodoFromTodoFormFields(request.todo)

        worker = TodosWorker(todosStore: TodoStore())
        worker?.addTodo(todoToAdd: todoToAdd) { (todos) -> Void in
            if let todos = todos {
                self.todos = todos
                let response = TodoDetail.AddTodo.Response(todos: todos)
                self.presenter?.presentAddTodo(response: response)
            }

            //        self.todoToEdit = todo
            //        let response = TodoDetail.UpdateTodo.Response(todo: todo!)
            //        self.presenter?.presentUpdateTodo(response: response)
        }
    }

    func getTodo(request: TodoDetail.GetTodo.Request) {
        let response = TodoDetail.GetTodo.Response(todo: todoToEdit)
        presenter?.presentGetTodo(response: response)
    }

    func updateTodo(request: TodoDetail.UpdateTodo.Request)
    {
        let todoToUpdate = buildTodoFromTodoFormFields(request.todo)

        worker = TodosWorker(todosStore: TodoStore())
        worker?.updateTodo(todoToUpdate: todoToUpdate) { (todos) -> Void in
            if let todos = todos {
                self.todos = todos
                let response = TodoDetail.UpdateTodo.Response(todos: todos)
                self.presenter?.presentUpdateTodo(response: response)
            }

            //        self.todoToEdit = todo
            //        let response = TodoDetail.UpdateTodo.Response(todo: todo!)
            //        self.presenter?.presentUpdateTodo(response: response)
        }
    }

    private func buildTodoFromTodoFormFields(_ todoFormFields: TodoDetail.TodoFormFields) -> Todo {
        var id = 1
        if let todo = worker?.fetchLastTodo() {
            id = todo.id
        }
        return Todo(id: id, todoContent: todoFormFields.todoContent, isDone: todoFormFields.isDone)
    }
}
