//
//  TodoDetailInteractor.swift
//  TodoCleanSwiftSample
//
//  Created by 60067667 on 2021/01/20.
//  Copyright (c) 2021 Nali. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TodoDetailBusinessLogic
{
    var todoToEdit: Todo? { get }
  func updateTodo(request: TodoDetail.UpdateTodo.Request)
}

protocol TodoDetailDataStore
{
    var todoToEdit: Todo? { get set }
}

class TodoDetailInteractor: TodoDetailBusinessLogic, TodoDetailDataStore
{
  var presenter: TodoDetailPresentationLogic?
  var worker: TodoDetailWorker?
    var todoToEdit: Todo?
  
  // MARK: Do something
  
  func updateTodo(request: TodoDetail.UpdateTodo.Request)
  {
    let todoToUpdate = buildTodoFromTodoFormFields(request.todo)

    worker = TodoDetailWorker(todoStore: TodoStore())
    worker?.updateTodo(todoToUpdate: todoToUpdate) { (todo) in
        self.todoToEdit = todo
        let response = TodoDetail.UpdateTodo.Response(todo: todo!)
        self.presenter?.presentUpdateTodo(response: response)
    }
  }

    private func buildTodoFromTodoFormFields(_ todoFormFields: TodoDetail.TodoFormFields) -> Todo {
        return Todo(todoContent: todoFormFields.todoContent, isDone: todoFormFields.isDone)
    }
}
