//
//  TodoDetailModels.swift
//  TodoCleanSwiftSample
//
//  Created by 60067667 on 2021/01/20.
//  Copyright (c) 2021 Nali. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum TodoDetail
{
    struct TodoFormFields {
        var todoContent: String
        var isDone: Bool
    }
    // MARK: Use cases

    enum AddTodo
    {
        // VC -> Interactor
        struct Request
        {
            var todo: TodoFormFields
        }
        // Interactor -> Presenter
        struct Response
        {
            var todos: [Todo]
        }
        // Presenter -> VC
        struct ViewModel
        {
            var todos: [Todo]
        }
    }

    // Todo Detail..
    enum GetTodo {
        struct Request {
        }
        struct Response {
            var todo: Todo?
        }
        struct ViewModel {
            struct DisplayedTodo {
                var todoContent: String
            }
            var displayedTodo: DisplayedTodo?
        }
    }

    enum UpdateTodo
    {
        // VC -> Interactor
        struct Request
        {
            var todo: TodoFormFields
        }
        // Interactor -> Presenter
        struct Response
        {
            var todos: [Todo]
        }
        // Presenter -> VC
        struct ViewModel
        {
            var todos: [Todo]
        }
    }
}
