//
//  TodoDetailViewController.swift
//  TodoCleanSwiftSample
//
//  Created by 60067667 on 2021/01/20.
//  Copyright (c) 2021 Nali. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TodoDetailDisplayLogic: class
{
    func displayAddTodo(viewModel: TodoDetail.AddTodo.ViewModel)
    func displayUpdateTodo(viewModel: TodoDetail.UpdateTodo.ViewModel)
    func displayGetTodo(viewModel: TodoDetail.GetTodo.ViewModel)
}

class TodoDetailViewController: UIViewController, TodoDetailDisplayLogic
{
    var interactor: TodoDetailBusinessLogic?
    var router: (NSObjectProtocol & TodoDetailRoutingLogic & TodoDetailDataPassing)?

    // MARK: Object lifecycle

    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
    {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }

    required init?(coder aDecoder: NSCoder)
    {
        super.init(coder: aDecoder)
        setup()
    }

    // MARK: Setup

    private func setup()
    {
        let viewController = self
        let interactor = TodoDetailInteractor()
        let presenter = TodoDetailPresenter()
        let router = TodoDetailRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }

    // MARK: Routing

    override func prepare(for segue: UIStoryboardSegue, sender: Any?)
    {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }

    // MARK: View lifecycle

    override func viewDidLoad()
    {
        super.viewDidLoad()
        getTodo() // List 화면에서 cell을 선택하였을 경우 선택한 cell의 정보를 가져온다.
    }

    func getTodo() {
        let request = TodoDetail.GetTodo.Request()
        interactor?.getTodo(request: request)
    }

    // MARK: Do something

    @IBOutlet weak var todoDetailTextView: UITextView!

    /// 저장 버튼 클릭
    @IBAction func touchSaveButton(_ sender: Any) {
        let todoContent = todoDetailTextView.text!

        let request = TodoDetail.UpdateTodo.Request(todo: TodoDetail.TodoFormFields(todoContent: todoContent))
        interactor?.updateTodo(request: request)
    }

    func displayAddTodo(viewModel: TodoDetail.AddTodo.ViewModel) {
        if !viewModel.todos.isEmpty {
            router?.routeToTodoList(segue: nil)
        }
    }

    /// 전 화면에서 선택했을 경우 textView에 선택한 내용 세팅해주고, 아니면 세팅 안됨.
    func displayGetTodo(viewModel: TodoDetail.GetTodo.ViewModel) {
        let displayedTodo = viewModel.displayedTodo
        todoDetailTextView.text = displayedTodo?.todoContent
    }

    func displayUpdateTodo(viewModel: TodoDetail.UpdateTodo.ViewModel)
    {
        router?.routeToTodoList(segue: nil)
    }


    // Error handling
    private func showTodoFailureAlert(title: String, message: String)
    {
        let alertController = UIAlertController(title: title, message: message, preferredStyle: .alert)
        let alertAction = UIAlertAction(title: "OK", style: .default, handler: nil)
        alertController.addAction(alertAction)
        showDetailViewController(alertController, sender: nil)
    }
}
