//
//  TodoListViewController.swift
//  TodoCleanSwiftSample
//
//  Created by 60067667 on 2021/01/19.
//  Copyright (c) 2021 Nali. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TodoListDisplayLogic: class
{
  func displaySomething(viewModel: TodoList.Something.ViewModel)
}

class TodoListViewController: UIViewController, TodoListDisplayLogic
{
  var interactor: TodoListBusinessLogic?
  var router: (NSObjectProtocol & TodoListRoutingLogic & TodoListDataPassing)?

    // MARK: Object lifecycle
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
  {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder)
  {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: Setup
  
  private func setup()
  {
    let viewController = self
    let interactor = TodoListInteractor()
    let presenter = TodoListPresenter()
    let router = TodoListRouter()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }
  
  // MARK: Routing
  
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    if let scene = segue.identifier {
      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
      if let router = router, router.responds(to: selector) {
        router.perform(selector, with: segue)
      }
    }
  }
  
  // MARK: View lifecycle
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
    doSomething()
  }

    var displayedTodos: [String] = ["aaa", "bbb", "ccc"] // TODO: 모델 상세화
  
  // MARK: Do something
  
  //@IBOutlet weak var nameTextField: UITextField!
  @IBOutlet weak var tableView: UITableView!
  
  func doSomething()
  {
    let request = TodoList.Something.Request()
    interactor?.doSomething(request: request)

    tableView.delegate = self
    tableView.dataSource = self
  }
  
  func displaySomething(viewModel: TodoList.Something.ViewModel)
  {
    //nameTextField.text = viewModel.name

  }
}

// MARK: - Table view

extension TodoListViewController: UITableViewDelegate, UITableViewDataSource {
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return displayedTodos.count
    }

    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let todo = displayedTodos[indexPath.row]
        let cell = tableView.dequeueReusableCell(withIdentifier: "TodoListCell", for: indexPath)
//        cell.textLabel?.text = todo
        return cell
    }


}
