//
//  TodoListModels.swift
//  TodoCleanSwiftSample
//
//  Created by 60067667 on 2021/01/19.
//  Copyright (c) 2021 Nali. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum TodoList
{
  // MARK: Use cases

    enum UpdateTodo {
        struct Request
        {
            var todo: Todo
        }
        struct Response
        {
            var todos: [Todo]
        }
        struct ViewModel
        {
            struct DisplayedTodo {
                var todoContent: String
                var isDone: Bool
            }
            var displayedTodos: [DisplayedTodo]
        }
    }
  
  enum FetchTodos
  {
    struct Request
    {
    }
    struct Response
    {
        var todos: [Todo]
    }
    struct ViewModel
    {
        struct DisplayedTodo {
            var todoContent: String
            var isDone: Bool
        }
        var displayedTodos: [DisplayedTodo]
    }
  }
}
