//
//  TodoListRouter.swift
//  TodoCleanSwiftSample
//
//  Created by 60067667 on 2021/01/19.
//  Copyright (c) 2021 Nali. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol TodoListRoutingLogic
{
    func routeToTodoDetail(segue: UIStoryboardSegue?)
}

protocol TodoListDataPassing
{
    var dataStore: TodoListDataStore? { get }
}

class TodoListRouter: NSObject, TodoListRoutingLogic, TodoListDataPassing
{
    weak var viewController: TodoListViewController?
    var dataStore: TodoListDataStore?

    // MARK: Routing

    // List -> Detail로 이동
    // 수정 or 추가의 경우가 있다.
    func routeToTodoDetail(segue: UIStoryboardSegue?)
    {
        if let segue = segue {
            let destinationVC = segue.destination as! TodoDetailViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToTodoDetail(source: dataStore!, destination: &destinationDS)
        } else {
            let storyboard = UIStoryboard(name: "Main", bundle: nil)
            let destinationVC = storyboard.instantiateViewController(withIdentifier: "TodoDetailViewController") as! TodoDetailViewController
            var destinationDS = destinationVC.router!.dataStore!
            // 중요!! 순서..
            passDataToTodoDetail(source: dataStore!, destination: &destinationDS)
            navigateToTodoDetail(source: viewController!, destination: destinationVC)
        }
    }

    // MARK: Navigation

    func navigateToTodoDetail(source: TodoListViewController, destination: TodoDetailViewController)
    {
        source.show(destination, sender: nil)
    }

    // MARK: Passing data
    
    func passDataToTodoDetail(source: TodoListDataStore, destination: inout TodoDetailDataStore)
    {
        destination.todos = source.todos
        // 셀을 선택했을 땐 여길 타서 destination의 todoEdit이 채워져있을 것이다.
        // 추가인 경우 selectedRow가 없어서 todoEdit이 nil일 것이다.
        if let selectedRow = viewController?.tableView.indexPathForSelectedRow?.row {
            // 수정일 때
            dataStore?.todoToUpdateIndex = selectedRow
            // destination: Detail
            // Detail DataStore에 List의 데이터를 전달한다.
            destination.todoToEdit = source.todos?[selectedRow]
            viewController?.tableView.deselectRow(at: IndexPath(row: selectedRow, section: 0), animated: false) // 선택 취소
        } else {
            // add일 때
            dataStore?.todoToUpdateIndex = nil
            destination.todoToEdit = nil
        }
    }
}
