//
//  TodoListPresenter.swift
//  TodoCleanSwiftSample
//
//  Created by 60067667 on 2021/01/19.
//  Copyright (c) 2021 Nali. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TodoListPresentationLogic
{
  func presentSomething(response: TodoList.Something.Response)
}

class TodoListPresenter: TodoListPresentationLogic
{
  weak var viewController: TodoListDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: TodoList.Something.Response)
  {
    let viewModel = TodoList.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
