//
//  TodoListInteractor.swift
//  TodoCleanSwiftSample
//
//  Created by 60067667 on 2021/01/19.
//  Copyright (c) 2021 Nali. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TodoListBusinessLogic
{
    func fetchTodos(request: TodoList.FetchTodos.Request)
    func updateTodo(request: TodoList.UpdateTodo.Request)
//    func getTodos(request: TodoList.GetTodo.Request)
    func getUpdatedTodo(request: TodoList.GetUpdatedTodo.Request)
}

protocol TodoListDataStore
{
    var todos: [Todo]? { get set } // 화면에 보여줄 todo list
    var todoToUpdateIndex: Int? { get set }
    var todoToUpdate: Todo? { get set }
}

class TodoListInteractor: TodoListBusinessLogic, TodoListDataStore
{
    var presenter: TodoListPresentationLogic?
    var worker: TodosWorker = TodosWorker(todosStore: TodoStore())
    var todos: [Todo]? // 화면에 보여줄 todo list
    var todoToUpdateIndex: Int?
    var todoToUpdate: Todo?

    /// worker을 통해서 저장된 Todo List를 가져온다.
    func fetchTodos(request: TodoList.FetchTodos.Request)
    {
        worker.fetchTodos{ (todos) -> Void in
            // 가져온 list를 interactor가 관리하는 todos에 넣어준다.
            self.todos = todos
            let response = TodoList.FetchTodos.Response(todos: todos)
            self.presenter?.presentFetchedTodos(response: response)
        }
    }

    func updateTodo(request: TodoList.UpdateTodo.Request) {
        
    }

//    func getTodos(request: TodoList.GetTodo.Request) {
//
//        let response = TodoList.GetTodo.Response(todos: todos!)
//        presenter?.presentTodo(response: response)
//
//    }

    func getUpdatedTodo(request: TodoList.GetUpdatedTodo.Request) {
        if let todoToUpdateIndex = todoToUpdateIndex {
            let response = TodoList.GetUpdatedTodo.Response(updatedIndex: todoToUpdateIndex, todo: todoToUpdate!)
            self.todoToUpdateIndex = nil
            self.todoToUpdate = nil
            presenter?.presentUpdatedTodo(response: response)
        } else {
            todos?.append(todoToUpdate!)
            let response = TodoList.GetUpdatedTodo.Response(updatedIndex: nil, todo: todoToUpdate!)
            presenter?.presentUpdatedTodo(response: response)
        }

    }
}
