//
//  TodoListRouter.swift
//  TodoCleanSwiftSample
//
//  Created by 60067667 on 2021/01/19.
//  Copyright (c) 2021 Nali. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol TodoListRoutingLogic
{
    func routeToUTodoDetail(segue: UIStoryboardSegue?)
}

protocol TodoListDataPassing
{
    var dataStore: TodoListDataStore? { get }
}

class TodoListRouter: NSObject, TodoListRoutingLogic, TodoListDataPassing
{
    weak var viewController: TodoListViewController?
    var dataStore: TodoListDataStore?

    // MARK: Routing

    func routeToUTodoDetail(segue: UIStoryboardSegue?)
    {
        if let segue = segue {
            let destinationVC = segue.destination as! TodoDetailViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToTodoDetail(source: dataStore!, destination: &destinationDS)
        } else {
            let storyboard = UIStoryboard(name: "Main", bundle: nil)
            let destinationVC = storyboard.instantiateViewController(withIdentifier: "TodoDetailViewController") as! TodoDetailViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToTodoDetail(source: dataStore!, destination: &destinationDS)
            navigateToTodoDetail(source: viewController!, destination: destinationVC)
        }
    }

    // MARK: Navigation

    func navigateToTodoDetail(source: TodoListViewController, destination: TodoDetailViewController)
    {
        source.show(destination, sender: nil)
    }

    // MARK: Passing data
    
    func passDataToTodoDetail(source: TodoListDataStore, destination: inout TodoDetailDataStore)
    {
        if let selectedRow = viewController?.tableView.indexPathForSelectedRow?.row {
            destination.todoToEdit = source.todos?[selectedRow]
        }
    }
}
