//
//  TodoListInteractor.swift
//  TodoCleanSwiftSample
//
//  Created by 60067667 on 2021/01/19.
//  Copyright (c) 2021 Nali. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TodoListBusinessLogic
{
    func fetchTodos(request: TodoList.FetchTodos.Request)
    func updateTodo(request: TodoList.UpdateTodo.Request)
    func getTodos(request: TodoList.GetTodo.Request)
}

protocol TodoListDataStore
{
    var todos: [Todo]? { get set }
}

class TodoListInteractor: TodoListBusinessLogic, TodoListDataStore
{
    var presenter: TodoListPresentationLogic?
    var worker: TodosWorker = TodosWorker(todosStore: TodoStore())
    var todos: [Todo]?

    // MARK: Do something

    func fetchTodos(request: TodoList.FetchTodos.Request)
    {
        worker.fetchTodos{ (todos) -> Void in
            self.todos = todos
            let response = TodoList.FetchTodos.Response(todos: todos)
            self.presenter?.presentFetchedTodos(response: response)
        }
    }

    func updateTodo(request: TodoList.UpdateTodo.Request) {
        
    }

    func getTodos(request: TodoList.GetTodo.Request) {

        let response = TodoList.GetTodo.Response(todos: todos!)
        presenter?.presentTodo(response: response)

    }
}
