//
//  TodoListPresenter.swift
//  TodoCleanSwiftSample
//
//  Created by 60067667 on 2021/01/19.
//  Copyright (c) 2021 Nali. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TodoListPresentationLogic
{
  func presentFetchedTodos(response: TodoList.FetchTodos.Response)
}

class TodoListPresenter: TodoListPresentationLogic
{
  weak var viewController: TodoListDisplayLogic?
  
  func presentFetchedTodos(response: TodoList.FetchTodos.Response)
  {
    // response to displayedTodos
    var displayedTodos: [TodoList.FetchTodos.ViewModel.DisplayedTodo] = []
    for todo in response.todos {
        let displayedTodo = TodoList.FetchTodos.ViewModel.DisplayedTodo(todoContent: todo.todoContent, isDone: todo.isDone)
        displayedTodos.append(displayedTodo)
    }

    let viewModel = TodoList.FetchTodos.ViewModel(displayedTodos: displayedTodos)
    viewController?.displayFetchedTodos(viewModel: viewModel)
  }
}
