//
//  TodoListInteractor.swift
//  TodoCleanSwiftSample
//
//  Created by 60067667 on 2021/01/19.
//  Copyright (c) 2021 Nali. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TodoListBusinessLogic
{
  func doSomething(request: TodoList.Something.Request)
}

protocol TodoListDataStore
{
  //var name: String { get set }
}

class TodoListInteractor: TodoListBusinessLogic, TodoListDataStore
{
  var presenter: TodoListPresentationLogic?
  var worker: TodoListWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: TodoList.Something.Request)
  {
    worker = TodoListWorker()
    worker?.doSomeWork()
    
    let response = TodoList.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
