//
//  TodoListViewController.swift
//  TodoCleanSwiftSample
//
//  Created by 60067667 on 2021/01/19.
//  Copyright (c) 2021 Nali. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TodoListDisplayLogic: class
{
  func displayFetchedTodos(viewModel: TodoList.FetchTodos.ViewModel)
}

class TodoListViewController: UIViewController, TodoListDisplayLogic
{
  var interactor: TodoListBusinessLogic?
  var router: (NSObjectProtocol & TodoListRoutingLogic & TodoListDataPassing)?

    // MARK: Object lifecycle
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
  {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder)
  {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: Setup
  
  private func setup()
  {
    let viewController = self
    let interactor = TodoListInteractor()
    let presenter = TodoListPresenter()
    let router = TodoListRouter()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }
  
  // MARK: Routing
  
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    if let scene = segue.identifier {
      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
      if let router = router, router.responds(to: selector) {
        router.perform(selector, with: segue)
      }
    }
  }
  
  // MARK: View lifecycle
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
    fetchTodos()
  }

    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
    }

    var displayedTodos: [TodoList.FetchTodos.ViewModel.DisplayedTodo] = []
  
  // MARK: Do something
  
  //@IBOutlet weak var nameTextField: UITextField!
  @IBOutlet weak var tableView: UITableView!

    func displayFetchedTodos(viewModel: TodoList.FetchTodos.ViewModel) {
        displayedTodos = viewModel.displayedTodos
        tableView.reloadData()
    }

  func fetchTodos()
  {
    let request = TodoList.FetchTodos.Request()
    interactor?.fetchTodos(request: request)
  }
}

// MARK: - Table view

extension TodoListViewController: UITableViewDelegate, UITableViewDataSource {
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return displayedTodos.count
    }

    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        configureCell(forRowAt: indexPath)
    }

    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        print(indexPath)
    }

    private func configureCell(forRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCell(withIdentifier: "TodoListCell", for: indexPath) as! TodoListCell
        cell.item = displayedTodos[indexPath.row]
        // cell.item에 DisplayedTodo 전달
        return cell
    }
}
