//
//  TodoListModels.swift
//  TodoCleanSwiftSample
//
//  Created by 60067667 on 2021/01/19.
//  Copyright (c) 2021 Nali. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum TodoList
{
    // MARK: Use cases

    enum UpdateTodo {
        struct Request
        {
            var todo: Todo
        }
        struct Response
        {
            var todos: [Todo]
        }
        struct ViewModel
        {
            struct DisplayedTodo {
                var todoContent: String
                var isDone: Bool
            }
            var displayedTodos: [DisplayedTodo]
        }
    }

    /// 저장된 Todo List를 모두 가져온다.
    enum FetchTodos
    {
        struct Request
        {
        }
        struct Response
        {
            var todos: [Todo]
        }
        struct ViewModel
        {
            /// List 화면에 보여줄 형식
            struct DisplayedTodo {
                var todoContent: String
                var isDone: Bool
            }
            var displayedTodos: [DisplayedTodo]
        }
    }

    enum GetTodo {
        struct Request
        {
        }
        struct Response
        {
            var todos: [Todo]
        }
        struct ViewModel
        {
            struct DisplayedTodo {
                var todoContent: String
                var isDone: Bool
            }
            var displayedTodos: [DisplayedTodo]
        }
    }

    enum GetUpdatedTodo {
        struct Request
        {
        }
        struct Response
        {
            var updatedIndex: Int?
            var todo: Todo
        }
        struct ViewModel
        {
            struct DisplayedTodo {
                var todoContent: String
                var isDone: Bool
            }
            var displayedTodo: DisplayedTodo
            var indexToUpdate: Int?
        }
    }
}
