# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MVVMRxTutorial' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MVVMRxTutorial
pod 'Alamofire'
pod 'RxSwift'
pod 'RxCocoa'
pod 'SDWebImage' 

  target 'MVVMRxTutorialTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MVVMRxTutorialUITests' do
    # Pods for testing
  end

end
